### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by acstache** [ltguide/CraftBukkit-MineBackup#1]
I'm not sure what the cause was. I loaded up Minebackup v0.5, edited the config to my liking, and sent the plugin on it's way. After about 6 or 7 minutes, I got hit with this error
http://pastie.org/3205564

Immediately following that error (with a 1 minute delay in between each iteration), I got the following line spamming the console:
"[INFO] [MineBackup]  - TaskProcess already working - it's already been a minute?!"
There wasn't much of a sign that it was going to fix itself anytime soon. I've reverted to v0.4.8.4 as that seems to still be chugging along nicely.

Also, here is the config.yml I was using with v0.5 if it would help at all.
http://pastie.org/3205574

Almost forgot: currently running CB 1597 (1.0 RB)

**Comment by ltguide** [comment]
Could you try v0.5.2 and see if it has the same problem?

**Comment by acstache** [comment]
I noticed another individual tried v0.5.2 and still got this. Should I wait for the time being to try it or should I still try it and see if I get different results?

**Comment by ltguide** [comment]
I think I've got it. [dev page](http://dev.bukkit.org/server-mods/minebackup/pages/v0-5-development/)

**Comment by acstache** [comment]
The first saves went off without an issue using 0.5.3 (and using the same config as above). I'll keep you posted on anything that might happen.

**Comment by ltguide** [comment]
Awesome, thanks :0
