### ISSUE TITLE
Backups Alerts (Not Displaying)

### ISSUE THREAD

**Issue by SirLostSpirit** [ltguide/CraftBukkit-MineBackup#15]
MineBackup will only show warnings on screen when an admin does  /minebackup NOW

**Comment by ltguide** [comment]
What do you mean? Could you post an example?

**Comment by SirLostSpirit** [comment]
There is not really anything that i can show. It will just show the info of the plugin on the console when it is on a timed backup. I can't really send you the stuff on the console because I updated to 1.2 and ... yea lol
If it continues on 1.2 I will send the pastebin.

**Comment by SirLostSpirit** [comment]
Oh i'm dumb, you just updated i'm gonna go test it now...

**Comment by ltguide** [comment]
Have you tried 0.5.8? It works with 1.2+

**Comment by SirLostSpirit** [comment]
:3 Yea and You Rock!!!

**Comment by ltguide** [comment]
I think you mean the "backup has started" "backup has ended" broadcasts. The way it spaces everything out, you could potentially get those messages merely a minute apart several times. I left it in the console since it could be pretty spammy.

**Comment by SirLostSpirit** [comment]
:( No offence to the customization that you are going for but I liked the old MineBackup better.....

**Comment by ltguide** [comment]
To use it like the old version, under default_actions, just set compress or copy to true. Any worlds/settings not specified under "worlds" will inherit from there.

**Comment by SirLostSpirit** [comment]
What about messages?

**Comment by ltguide** [comment]
Oh, I thought you meant the actual config was too customizable. The messages are another story. It splits everything up to keep from doing a lot of things at once therefore bogging the server down all at once... making the message a warning of big lag. If there is any lag during saving in 0.5+ it should be much shorter.

**Comment by SirLostSpirit** [comment]
This is how I feel right now = http://youtu.be/Y323-b722So 

I'm making a simplified Config and another file for msgs

**Comment by SirLostSpirit** [comment]
almost done, I'm putting allot of thought into how it will be for others. No matter if they are very smart with their server or the opposite.....

**Comment by ltguide** [comment]
I want to figure out a way to make it easy to setup the defaults as well. I've thought of making a quick gui to write the config.

**Comment by SirLostSpirit** [comment]
http://www.mediafire.com/?2vwv85eb96dlj6q http://www.mediafire.com/?ikasofw9zbfr4qj   something like that, i'd rather this then a gui

**Comment by SirLostSpirit** [comment]
Does that config seem better?

**Comment by SirLostSpirit** [comment]
Config:
http://pastebin.com/ECCFYVtz 

Msg:
http://pastebin.com/gXnJRDTY

**Comment by ltguide** [comment]
The bukkit configuration classes don't support comments in the middle of the file. (and on a side-note, they are picky: #_space_text. It took me a long time to figure that out lol)

I'm afraid to add too many more keys (save AND save_delay (which i would call _interval), etc. There are already a lot of complaints about the new version being too complicated and possibly too customizable.

I am however probably going to split the commands and messages (renamed to 'strings') sections over to a messages.yml. And then add the backup messages as well.

**Comment by ltguide** [comment]
Done, sort-of like you suggested :0
