### ISSUE TITLE
Plugin doesn't do anything

### ISSUE THREAD

**Issue by tobi1449** [ltguide/CraftBukkit-MineBackup#22]
After updating from the old 4.8.X version if just discovered that the plugin hasn't been making any backups at all.
I don't know why, I just tried to figure out if it is a config problem and I'm stuck, triggering a backup with /backup now doesn't do anyhting
Here's my current config

<code>default_actions:
  save: true
  copy: true
  compress: true
  cleanup: true
  dropbox: false
default_settings:
  save: 15m
  copy: 1h
  compress: 1h
  compression_level: 9
  keep: 30d
worlds:
  world:
  default_actions: true
  default_timings: true
  save: true
  compress: true
  dropbox: false
  compression_level: 9
  save_time: 15m
  compress_time: 1h
  keep: 30d
others:
  plugins:
    copy: false
    compress: false
    dropbox: false
    exclude-folders:
    - tiles
    exclude-types:
    - jar
    - lck
directories:
  worlds: .
  others: .
  destination: ./minebackup
destination:
  format: '%Y-%M-%D_%H-%m-%S'
  prepend-world: true
messages:
  prefix: '&e[MineBackup]&f'
  busy: An action is currently in progress. Try again in a few seconds.
  syntax: '&6Syntax: &f%s &6--&e %s'
  permission: '&cYou do not have permission.'
  status: '&6%s: &f%s (&edirty: &f%s) %s'
  status_action: '&6%s: &f%s (&e%s&f)&6; '
  status_time_under: waiting %s
  status_time_over: soon (%s over)
  status_time_none: not scheduled
  status_note: New actions will be scheduled once a minute.
  backup_now: All backup actions will start momentarily. (%s)
  backup_soon: All backup actions added to the queue. (%s)
  backup_next: The next backup action has been started early. (%s)
  backup_done: All backup actions have completed.
  reload: '&aReloaded configuration. (%s)'
  dropbox: Dropbox authentication completed. (%s)
commands:
  status:
    description: Display the scheduled time and interval for each action in the queue.
  now:
    description: Expire all action times and trigger them NOW.
    broadcast: users
  soon:
    description: Expire all action times so that they will trigger on the following queue checks.
    broadcast: admins
  next:
    description: Trigger the next action in the queue. If no time is expired then nothing will happen.
    broadcast: admins
  reload:
    description: Reload configuration and reset queue to configured intervals.
    broadcast: false
  dropbox:
    description: Add Dropbox authentication tokens. Visit https://minebackup-dropbox.appspot.com/ for values.
    broadcast: false
debug: false
version-nomodify: 0.5.5</code>

**Comment by ghost** [comment]
First of all the command is "/minebackup now" and this doesn't work on R6 or above builds.

Heres my config.

# For an explanation of these settings, visit https://github.com/ltguide/CraftBukkit-MineBackup/wiki/Configuration

default_actions:
  save: false
  copy: false
  compress: false
  cleanup: false
  dropbox: false
default_settings:
  save: 1h
  copy: 2h
  compress: 3h
  compression_level: 9
  cleanup: '2:00'
  dropbox: '3:00'
  keep: 56
worlds:
  world:
    save: true
    save: 30m
    compress: true
    compress: 2h
  world_nether:
    save: true
    compress: true
  world_the_end:
    save: true
    compress: true
others:
  plugins:
    copy: false
    compress: true
    dropbox: false
    exclude-folders:
    - tiles
    exclude-types:
    - jar
    - lck
directories:
  worlds: .
  others: .
  destination: ./minebackup
destination:
  format: '%M-%D_%H-%m'
  prepend-world: true
messages:
  prefix: '&e[MineBackup]&f'
  busy: An action is currently in progress. Try again in a few seconds.
  syntax: '&6Syntax: &f%s &6--&e %s'
  permission: '&cYou do not have permission.'
  status: '&6%s: &f%s (&edirty: &f%s) %s'
  status_action: '&6%s: &f%s (&e%s&f)&6; '
  status_time_under: waiting %s
  status_time_over: soon (%s over)
  status_time_none: not scheduled
  status_note: New actions will be scheduled once a minute.
  backup_now: All backup actions will start momentarily. (%s)
  backup_soon: All backup actions added to the queue. (%s)
  backup_next: The next backup action has been started early. (%s)
  backup_done: All backup actions have completed.
  reload: '&aReloaded configuration. (%s)'
  dropbox: Dropbox authentication completed. (%s)
commands:
  status:
    description: Display the scheduled time and interval for each action in the queue.
  now:
    description: Expire all action times and trigger them NOW.
    broadcast: users
  soon:
    description: Expire all action times so that they will trigger on the following queue checks.
    broadcast: admins
  next:
    description: Trigger the next action in the queue. If no time is expired then nothing will happen.
    broadcast: admins
  reload:
    description: Reload configuration and reset queue to configured intervals.
    broadcast: false
  dropbox:
    description: Add Dropbox authentication tokens. Visit http://minebackup-dropbox.appspot.com/ for values.
    broadcast: false
debug: false
version-nomodify: 0.5.5

**Comment by dredhorse** [comment]
hi, try 0.5.7 from the comments which has ftp and R5
