### ISSUE TITLE
java.lang.InterruptedException

### ISSUE THREAD

**Issue by ghost** [ltguide/CraftBukkit-MineBackup#24]
Hello

I am using the RemoteToolKit wrapper and i used the .restart command and i got this error.

17:10:02 [INFO] [MineBackup] Disabling MineBackup v0.5.8[0m
17:10:02 [SEVERE] [MineBackup] ---------------------------------------[0m
17:10:02 [SEVERE] [MineBackup] java.lang.InterruptedException[0m
17:10:02 [SEVERE] [MineBackup]  java.lang.Object.wait(Native Method)[0m
17:10:02 [SEVERE] [MineBackup]  org.bukkit.craftbukkit.scheduler.CraftFuture.get(CraftFuture.java:57)[0m
17:10:02 [SEVERE] [MineBackup]  org.bukkit.craftbukkit.scheduler.CraftFuture.get(CraftFuture.java:47)[0m
17:10:02 [SEVERE] [MineBackup]  ltguide.minebackup.configuration.Persist.isDirty(Persist.java:56)[0m
17:10:02 [SEVERE] [MineBackup]  ltguide.minebackup.threads.TaskProcess.checkQueue(TaskProcess.java:72)[0m
17:10:02 [SEVERE] [MineBackup]  ltguide.minebackup.threads.TaskProcess.checkQueue(TaskProcess.java:63)[0m
17:10:02 [SEVERE] [MineBackup]  ltguide.minebackup.threads.TaskProcess.runOnce(TaskProcess.java:115)[0m
17:10:02 [SEVERE] [MineBackup]  ltguide.minebackup.threads.TaskProcess.run(TaskProcess.java:111)[0m
17:10:02 [SEVERE] [MineBackup]  org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)[0m
17:10:02 [SEVERE] [MineBackup]  java.lang.Thread.run(Thread.java:636)[0m
17:10:02 [SEVERE] [MineBackup] ---------------------------------------[0m

If you need any more info please ask. We are running on CB build 2063 1.2.3. Minebackup 0.5.8

**Comment by ltguide** [comment]
mmmm that's some good timing. The sync thread was killed while it was running by the restart. I should be able to catch that error.

**Comment by ghost** [comment]
Cool, thanks. Hope you can add some fix for that :D Hasn't happened again luckly :D

**Comment by ltguide** [comment]
OK, next release it will just output to debug that it happened, so as to not complain so loudly.
