### ISSUE TITLE
Config reset - Invalid setup

### ISSUE THREAD

**Issue by ghost** [ltguide/CraftBukkit-MineBackup#26]
Just messing around with the setting and I configured it incorrectly and it got totally reset to default.

Can you somehow avoid this?

Using MineBackup 0.5.8 CB 1.2.3 Build 2072

**Comment by ghost** [comment]
Also I regenerated the config files, shut down the server, configured it like this (I hope this is a valid configuration):

# For an explanation of these settings, visit https://github.com/ltguide/CraftBukkit-MineBackup/wiki/Configuration

default_actions:
  save: true
  copy: false
  compress: true
  cleanup: true
  dropbox: false
  ftp: false
default_settings:
  save: 1m
  copy: 2h
  compress: 2m
  compression_level: 9
  cleanup: '2:00'
  dropbox: '3:00'
  ftp: '3:30'
  keep: 3
worlds:
  world:
    save: true
    save: 1m
    compress: true
    compress: 2m
    cleanup: true
    keep: 3
  world_nether:
    save: true
    save: 1m
    compress: true
    compress: 2m
    cleanup: true
    keep: 3
  world_the_end:
    save: true
    save: 1m
    compress: true
    compress: 2m
    cleanup: true
    keep: 3
others:
  plugins:
    copy: false
    compress: true
    compress: 2m
    dropbox: false
    exclude-folders:
    - tiles
    exclude-types:
    - jar
    - lck
directories:
  worlds: .
  others: .
  destination: ./minebackup
destination:
  format: '%Y-%M-%D_%H-%m-%S'
  prepend-world: false
ftp:
  server: ftpserver:21
  path: /
  username: user
  password: '123'
messages:
  prefix: '&e[MineBackup]&f'
  syntax: '&6Syntax: &f%s &6--&e %s'
  permission: '&cYou do not have permission.'
  reload: '&aReloaded configuration. (%s)'
  busy: An action is currently in progress. Try again in a few seconds.
  status: '&6%s: &f%s (&edirty: &f%s) %s'
  status_action: '&6%s: &f%s (&e%s&f)&6; '
  status_time_under: waiting %s
  status_time_over: soon (%s over)
  status_time_none: not scheduled
  status_note: New actions will be scheduled once a minute.
  backup_now: All backup actions will start momentarily. (%s)
  backup_soon: All backup actions added to the queue. (%s)
  backup_next: The next backup action has been started early. (%s)
  backup_done: All backup actions have completed.
  dropbox: Dropbox authentication completed. (%s)
commands:
  status:
    description: Display the scheduled time and interval for each action in the queue.
  now:
    description: Expire all action times and trigger them NOW.
    broadcast: users
  soon:
    description: Expire all action times so that they will trigger on the following queue checks.
    broadcast: admins
  next:
    description: Trigger the next action in the queue. If no time is expired then nothing will happen.
    broadcast: admins
  reload:
    description: Reload configuration and reset queue to configured intervals.
    broadcast: false
  dropbox:
    description: Add Dropbox authentication tokens. Visit https://minebackup-dropbox.appspot.com/ for values.
    broadcast: false
debug: true
start_covered_in_dirt: false
version-nomodify: 0.5.8

And after the settings were loaded like it said in the console, this is all that was put into the persist.dat file:

others:
  plugins:
    dirty: false
worlds:
  world:
    dirty: false
  world_nether:
    dirty: false
  world_the_end:
    dirty: false

Hope this helps in any way

**Comment by ltguide** [comment]
It checks for version-nomodify and writes the default when it doesn't exist. Problem is when there is an error loading the config then version-nomodify isn't going to exist.

Ok, next release it will copy the config to config.yml.invalid, then overwrite the original. A message will be output that says this as well :)

**Comment by ghost** [comment]
Thanks! When would the next release with some timing improvements come out?
