### ISSUE TITLE
Can't change strings

### ISSUE THREAD

**Issue by natinusala** [ltguide/CraftBukkit-MineBackup#30]
Hello,

I've modified the plugin's strings in strings.yml but the plugin seems to don't look at it, the in-game messages are still the same...

**Comment by ltguide** [comment]
The text changed when I edited messages.status_note (/mbck status always displays) and commands.status.description in strings.yml. I tested from a cold start and with /mbck reload. What does your config look like? You might need ' ' quotes around the line. You didn't get a console message about bad config did you?

**Comment by natinusala** [comment]
Here is my strings.yml file : http://pastebin.com/xWyJbYa8

There is an error in it, but where ?

**Comment by ltguide** [comment]
I think since you have french characters in it the encoding was changed to unicode or such. You should be able to do a Save as... in Notepad and choose ANSI as the encoding.

**Comment by natinusala** [comment]
The file is already in ANSI =/ 

...it was the "ç" which was making the pluging bugging.

Thanks, that's a great plugin !

**Comment by ltguide** [comment]
Huh. That character works on my computer. Weird.

**Comment by dredhorse** [comment]
hmm anything like this? https://bukkit.atlassian.net/browse/BUKKIT-1466

it depends on the os and I think even the java version... as I don't have the issue neither on my windows box (where I develop) not on the Debian? I run our server on.

**Comment by natinusala** [comment]
The file was in ANSI, maybe in UTF-8 it would work better.

**Comment by dredhorse** [comment]
well it looks like this is hit and miss atm with special characters :-( https://github.com/Bukkit/Bukkit/pull/453?_nid=39998759#issuecomment-4975146
