### ISSUE TITLE
Question - Compress & copy while backuping ?

### ISSUE THREAD

**Issue by natinusala** [ltguide/CraftBukkit-MineBackup#31]
Hello,

Is there a way to tell to the plugin to copy & compress the backups juste after creating it, insted of scheduling it ?

Thanks !

**Comment by ltguide** [comment]
What do you mean by "just after creating it?"

**Comment by natinusala** [comment]
When the backup process is launched, it would be nice to backup, copy and compress almost "at the same time", instead of doing it separately with a 30min gap.
