### ISSUE TITLE
[feature] root files backup

### ISSUE THREAD

**Issue by PrincessKarlotta** [ltguide/CraftBukkit-MineBackup#32]
It would be so great to have the option to backup the important root files (whitelist, server log, banned lists... etc). My host wipes out logs every night at 2AM so when we have issues, I can't go look at the logs and it's driving me nuts. You're my only chance!

Thank you :)

**Comment by ltguide** [comment]
added to next release

**Comment by PrincessKarlotta** [comment]
Awesome!!! Million thanks :)
