### ISSUE TITLE
Longer intervals?

### ISSUE THREAD

**Issue by lipe123** [ltguide/CraftBukkit-MineBackup#38]
I want to backup my world files every 2 or 3 days only, not every day.

Is there a way to do this already?

**Comment by ltguide** [comment]
Yeah, it will accept that. You can use 3d as a shortcut if you want.

**Comment by lipe123** [comment]
sweet! please add that to the help page thing cause it only mentions hours on there.

Oh I forgot to ask also, is it possible to still specify a time to run also then?

**Comment by ltguide** [comment]
No, it'll only take one or the other. It would add a lot of complexity to config it, I think.
