### ISSUE TITLE
Not scheduled?

### ISSUE THREAD

**Issue by commanderAIK** [ltguide/CraftBukkit-MineBackup#40]
Hello,
I've found a problem with this plugin.  AFter I successfully reloaded the config: here it is

http://pastebin.com/RSu96R47

I am getting this message when I see the status /backup status:

http://pastebin.com/eur490eT

It doesn't save or copy or anything.

I'm sorry if this is an easy answer, but how do I fix this?

Thanks,
commanderAIK

**Comment by cecell** [comment]
I'm having the same problem.  When adding worlds to the config file then using /minebackup reload it won't schedule the new world at all.  I have deleted persist.dat and then have even tried shutting the server down completely, deleting persist.dat and then booting again still with no luck.  One thing is clear: /minebackup reload is not bringing in new worlds.  I'm not even 100% sure if it is updating the actions or times for actions.
