### ISSUE TITLE
[MineBackup] % detected old map format files

### ISSUE THREAD

**Issue by o0Julia0o** [ltguide/CraftBukkit-MineBackup#49]
I get the following message after updating to Version 5.9.3 (before i had 5.9.0):

---

"[MineBackup] % detected old map format files (.\MYWORLD); once backed up, remove level.dat_mcr and *.mcr files from \region

2012-06-02 17:39:01 [WARNING] [MineBackup] % detected old map format files (.\MYWORLD_nether); once backed up, remove level.dat_mcr and *.mcr files from DIM-1\region
## 2012-06-02 17:39:01 [WARNING] [MineBackup] % detected old map format files (.\MYWORLD_the_end); once backed up, remove level.dat_mcr and *.mcr files from DIM1\region"

What does it mean? Do i have to delete this files from now on, after future backups? So everytime Minebackup saves my World, i have to delete this files?

Or do i have to delete this files in my original World - 1 time? But can i do that, without loosing important data?

thx 

Julia :)

**Comment by acstache** [comment]
it means in the actual world's region folder. With 1.2 and the map format update, the files are now all .mca while the .mcr files aren't ever used anymore

**Comment by o0Julia0o** [comment]
Oh thx :) I have f.e. a r.-1.-1.mcr & a r.-1.-1.mca. But i only have the level.dat_mcr. Do i have to rename it in level.dat_mca? Or is the level.dat_mca named: level.dat since 1.2?

Julia :)

**Comment by acstache** [comment]
Umm, I'm not sure about the level.dat_mcr, as I have just the r.-1.-1.mca etc files in the region folder, but in the world folder I simply have level.dat and level.dat_old. Both of them have been accessed recently (within the past couple of days), so I guess they're both used on a regular basis. What's the date modified on the level.dat_mcr?

**Comment by o0Julia0o** [comment]
oh yes, the file is very old - from march. So i think the old format had been: level.dat_mcr & the new format is: level.dat & level.dat_old. Thx acstache :)
