### ISSUE TITLE
PEX with MB 5.3 error

### ISSUE THREAD

**Issue by Wondrej** [ltguide/CraftBukkit-MineBackup#5]
hey, Iam testing your newest version 0.5.3 and I just got this error when using /minebackup now  through console window.

http://pastebin.com/Yv4XM0YJ backup was successful It seems that problem is somewhere between chatmanager and broadcasting message... Don't know what caused it

http://pastebin.com/j6D49ZNj this is my config file. I have some issues with it too, but those are just things that I don't understand properly, will start another ticket on them so this one is clearly for the PEX error.

**Comment by ghost** [comment]
Hmm its working great for me. Running PEX 1.17 Minebackup 0.5.3

Whats your CB version? I am on 1776, its the latest stable version for me  that doesn't give an error when reloading the server.

Link - http://repo.bukkit.org/content/groups/repo/org/bukkit/craftbukkit/1.1-R1-SNAPSHOT/craftbukkit-1.1-R1-20120117.184841-62.jar

What is you CB version?
Looks like your Permissions manager isn't accessable. Are you editing something in the jar file or something?

Also maybe update WorldEdit? 5.1 is out

Also you can turn on debug mode in minebackup maybe that gives more info :D

**Comment by ghost** [comment]
Hmm the plugin saving is still broken, have to report that again.

**Comment by Wondrej** [comment]
Iam using bukkit craftbukkit-1.1-R1-20120119.071633-68.jar (not sure what version is that now that jenkins is down)
I wasn't editing any jar file and the error didn't occure on reload but after "/minebackup now" it mighthave been some one time error, I'll try to reproduce it.

**Comment by Wondrej** [comment]
after trying command again its working fine... I dont understand. Well, I will report if anything else will happen. Thank you for response

**Comment by ltguide** [comment]
So this is what you did?
    /minebackup now
    /reload
    /minebackup now
    <error>

Looking at the stracktrace, I'd say that something broke with PEX during the reload. See how it leaves MineBackup, goes to CB, then heads to PEX to crash?

[SEVERE]    at ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.hasPermission(PermissiblePEX.java:123)
[SEVERE]    at org.bukkit.craftbukkit.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:66)
[SEVERE]    at org.bukkit.craftbukkit.CraftServer.broadcast(CraftServer.java:816)
[SEVERE]    at ltguide.minebackup.MineBackup.broadcast(MineBackup.java:130)

**Comment by ghost** [comment]
Only thing that I know is that any CB release higher then 1776 which i use breaks the plugins on reload They just go on error spree :D but 1776 works great. Thats the NR.62 snapshot

**Comment by ghost** [comment]
I do /minebackup reload after changing any settings and then /minebackup now.

Can you have a look at my other too tickets? mostly the one with the plugin backup error?

Thanks. Maybe I am doing something wrong. You can suggest me stuff or add me niftygamerz@live.com and ask stuff :d

**Comment by Wondrej** [comment]
these new releases are mess... I hope RB will be out soon.
and yes 

/minebackup now
 /reload
 /minebackup now

is what I've done, also with change of config of minebackup before reloading server

**Comment by ltguide** [comment]
I guess it must be what KJanar said. You are using .68 and anything after .62 causes /reload errors.

**Comment by Wondrej** [comment]
ok, I will go back to 62 anyway all the newest verison up to 71 (current) are not unloading chunks... so Iam having around 18000 loaded chunks with 8 people online... impressive huh?

anyway thank you for commenteries. and for solution.
