### ISSUE TITLE
world exclude-path

### ISSUE THREAD

**Issue by balderdk** [ltguide/CraftBukkit-MineBackup#55]
hi i would like to suggest the exclude-path attribute gets added to the world backup's as well so it's not only plugin and root that has the option.

This is mainly because of plug-ins like mcmmo they generate alot of "block data" basically it's just information on if the block is naturally there or placed by a user, and is not important but they do take up considerably amount's of space in the backup that we can live without.

**Comment by umarth** [comment]
I have the same problem

**Comment by ltguide** [comment]
Just add the exclude keys and it should apply the filter.

**Comment by balderdk** [comment]
Well if it was that easy i wouldn't be writing on here...

I have of course already tried that and it does not work.
