### ISSUE TITLE
Console Unale to force backup

### ISSUE THREAD

**Issue by patrick-hill** [ltguide/CraftBukkit-MineBackup#56]
From the console, /minebackup now, returns "You do not have permission".

Is it possible to allow the console to automatically have permissions?

**Comment by ltguide** [comment]
It uses whatever permissions system you have. Most grant console full permissions by default.

**Comment by patrick-hill** [comment]
For Bukkit, the console is automatically OP. I use PermissionsBukkit and haven't had to give "Console" any permissions as that is a little absurd.
The questions now is why does MineBackup behave in this manner ? I'll be sure to let you know what i find out.
