### ISSUE TITLE
Confusing config

### ISSUE THREAD

**Issue by Wondrej** [ltguide/CraftBukkit-MineBackup#6]
Problem might be on my side, and probably is :) but I just dont understand some features of new config file and perhaps you can explain them. This not a ticket, its morealike commentary. So I will go one by one while using your config file from https://github.com/ltguide/CraftBukkit-MineBackup/wiki/Configuration:

first part is ok, I understand that these are setting for everything unless its written otherwise in world section:
default_actions:
  save: false
  copy: false
  compress: false   ###From what I understand this is interval of backup, why it is called compress? also default setting as false is kindof confusing, usually when someone is set as false then other setting would be true, right?
  dropbox: false
default_settings:
  save: 15m  
  copy: 1h     #### what exactly copy does? copy what and where?
  compress: 1h
  compression_level: 9
  dropbox: '3:00'
  keep: 24

Ok and now for worlds, I dont understand why  worlds has less default options, should I add them? are they taken from default settings if not set? Or unnecessary in this case?

worlds:
  someworldname:   #### should I change this to my world name? when I changed it minebackup created it again...
    save: true
    compress: true  #### now here compress is true? shouldn't it be 3h or something?
    dropbox: true
  someworldname_nether:
    save: 30m
    compress: 3h
    keep: 8 ### here you set keep 
  someworldname_the_end:
    save: 30m
    copy: 6h
    keep: 4

rest of config is alright.... so there are my commentaries. As I said, maybe Iam just slow with understanding it. But also it might help to make it easier to understand :)

**Comment by ghost** [comment]
OK i am going to help as much as i can :D

The "default_actions" actions apply for all the maps in the "worlds:" list unless set different under each world.
save: means that it will save the map its like the console command "save-all" it just saves unsaved chunks and blocks to the map folder (no zipping)
copy: means it will copy the world folder to the minebackup folder or what ever folder you choosed to store backups.
compress: means the plugin will compress (zip) the map file and but it into the minebackup folder.
dropbox: this one im not so sure what it does and how it works, it saves the map to the dropbox account but havent tried it.
the "default_settings:" apply to all worlds in the "worlds:" list unless specified differently under each map.
save: 30m means all the maps will be "save-all" saved to the world folder
copy: 2h means the map folders will be saved into the minebackup folder (no zipping)
compress: 2h means the maps will be compressed into a zip file and moved to the minebackup folder.
compress_level: 9 means the compression level
dropbox: '3:00' means the time when it is saved to the dropbox account i guess
keep: 12 means it will keep 12 copies of every map version (i think)

So if you just want folders without compression only use copy: or compress with compress lvl or 0 but it will still zip.

This is my worlds setup - 
worlds:
  world:
    save: true
    compress: true
  world_nether:
    save: true
    compress: true
  world_the_end:
    save: true
    compress: true
  survival:
    save: true
    compress: true
  creative:
    save: true
    compress: true

I guess if you want you can specify a custom time under each map like - 
worlds:
  world:
    save: true
    compress: true
    save: 15m
    compress: 3h

So it would be logical to save the unsaved chunks to the map file with save: and then copy: or compress: the folder into the minebackup folder.

This is just my ideas and the way I understand. I might be wrong. The config is a bit confusing and no comments but with testing you can figure it out :D

**Comment by Wondrej** [comment]
thanks that somewhat helped.

**Comment by ltguide** [comment]
`save` - tells server to flush map to disk
`copy` - literally a copy of all the files
`compress` - a zip of all the files
`dropbox` - (I recommend using a time not interval) uploads last _compress_ to Dropbox account

The value of each setting in `default_settings` will be the default that is passed down to each world/other. Each takes a time interval (except keep and compression_level).

Then `default_actions`, which takes true/false, controls whether that 'action' is turned on automatically for worlds/others. If you turn on an action here but don't want certain worlds to do it, then you set it to false in the worlds/others config.

Under `worlds`/`others`, you can set true/false to control whether or not it inherits the value from `default_settings`. Or you can manually set a value as needed.

**Comment by Wondrej** [comment]
ok, thank you copy is something that I wont be using for sure. Iam ok with the .zip files.

and thanks for your patiens... its just too much with all these new updates and every plugin changing everything. 
Also, you did a good job with minebackup, keep it rolling.

**Comment by ltguide** [comment]
Copy is there for the servers that can't handle compression (old or single-core processor) or don't have the ram to hold the zip as it is created.

It needed to change :) The previous way of doing every backup action at once added lag to a lot of servers.
