### ISSUE TITLE
Incompatibility with KeepChunksInRam and ChunkKeeper

### ISSUE THREAD

**Issue by Tych0n** [ltguide/CraftBukkit-MineBackup#68]
Prevents them from correct work, i've removed all plugins except ChunkKeeper and then started to add one by one back. And when i added MineBackup, ChunkKeeper stopped working. I tested it with KCIR - the same problem.

**Comment by lipe123** [comment]
It seems this is also affecting traincarts where trains keep chunks loaded around them. Could you please look into this?
