### ISSUE TITLE
Universal Setting Section (PEX Based)

### ISSUE THREAD

**Issue by ghost** [ltguide/CraftBukkit-MineBackup#8]
Also I have a great new idea. I see that you have a setting section called "others:" and under it there is only plugins settings so I was thinking that maybe you can add a feature to backup custom files and databases and we can add those under the "others:" like - 
others:
  plugins:
    copy: false
    compress: true
    dropbox: false
    exclude-folders:
    - tiles
    exclude-types:
    - jar
  custom_db:
    compress: true
    compress: 2h

And also be able to set custom directories:
directories:
  worlds:
    world:
      location: ./custom_directory
      destination: ./minebackup 1 (should the directories support spaces?)
    world_nether:
      location: ./custom_directory2
      destination: ./minebackup 2 (should the directories support spaces?)
    plugins:
      location: .
      destination: ./backup_plugins
    other:
      location: ./custom_database
      destination: ./database

And maybe even mix those 2 together and have one universal section where everything is set up under directories (time, interval locations and etc)

directories:
  worlds:
    world:
      location: ./custom_directory
      destination: ./minebackup 1 (should the directories support spaces?)
      save: true
      save: 2h
      compress: true
      compress: 3h

Thanks mate, good plugin. Hope you consider these good ideas :D Then this would be better then that plugin called Backup.

**Comment by ltguide** [comment]
I commented on this in #7, but I'll paste it here for convenience.

The `others` section actually works on whatever folder name you add to it. 'plugins' is not special in the code. It should work if you add another folder name next to plugins. I haven't tested it but I assume that you should be able to do parent/child: etc.

The differences between `worlds` and `others` is the base path to the folders and the lack of processing `save` as an action.
