### ISSUE TITLE
MB 5.3 not unloading chunks

### ISSUE THREAD

**Issue by Wondrej** [ltguide/CraftBukkit-MineBackup#9]
I was talking about this in other ticket, but now I've located what is causing it...
When minebackup 0.5.3 is running on my server chunks aren't unloading, that causing large usage of memory and overloading server. I've ended up with over 18000 chunks loaded with only 4-5 online within few hours. Problems also started when I started using Minebackup 5.3. 

this is my confing file http://pastebin.com/ZTDASK1d

and list of all my active plugins
 Plugins: UltraBan, RedstoneClockDetector, LogBlockQuestioner, xAuth, XRayInformer, WorldEdit, WorldGuard, SimpleChestLock, PermissionsEx, Permissions, Vault, ChatManager, Modifyworld, WorldGuardFlagger, AdminCmd, LogBlock, MobArena, dynmap, Dynmap-WorldGuard

**Comment by ltguide** [comment]
What is the server version line from the console?

**Comment by Wondrej** [comment]
Its this version craftbukkit-1.1-R1-20120117.184841-62 , but I had the same problem with 3 newer releases. First I thought it was problem on bukkit side, but now Iam positive its done by Minebackup
Also I've noticed massive drop in RAM usage you can see for yourself here, arrow points to a time where I removed Minebackup. There is probably something in the code that causes dramatic usage of RAM that should be removed or fixed.
http://i41.tinypic.com/2e51pww.jpg

**Comment by ltguide** [comment]
I mean the CB version so I can test it with what you are running.

**Comment by Wondrej** [comment]
previous comment updated... this is number from console from last server start git-Bukkit-1.0.1-R1-82-g8f7360b-b1776jnks (MC: 1.1) (Implementing API version 1.1-R1-SNAPSHOT)

**Comment by ltguide** [comment]
Should be fixed in the latest version. Link is on the  [dev page](http://dev.bukkit.org/server-mods/minebackup/pages/v0-5-development/).

**Comment by Wondrej** [comment]
Will test it out tomorow, I'll let you know about any futher problems, thank you for fixing thou :)

**Comment by ltguide** [comment]
Of course :) I didn't realize that the server didn't unload chunks on its own when auto save is off.

**Comment by ltguide** [comment]
Oh yeah, if you turn on the debug option it'll tell you how many chunks were unloaded when it saves.

**Comment by Wondrej** [comment]
Iam using admincmd's /memory command to see loaded chunks, ticks and this kind of stuff, but thanks for heads up
